### PR TITLE
renamed to XRViewer

### PR DESCRIPTION
**Pull request by blairmacintyre**
Changed ArDemo to XRViewer everywhere (except pods)
Added new icon and splash

### CODE REVIEW

**Comment by TrevorFSmith** [comment]
Should ArDemo.xcodeproj, ArDemo.xcworkspace, and XRDemo.xcodeproj still be in the repo?

**Comment by blairmacintyre** [comment]
No, they shouldn't be.  But because I'm a dork and use the stupid Github Desktop app, the fact that I removed them did not get pushed up.

**Comment by blairmacintyre** [comment]
I have these files:
untitled

**Comment by TrevorFSmith** [comment]
Ok, I did a clean clone and the old files are gone.

**Comment by TrevorFSmith** [comment]
Now it fails when finding CocoaLumberjack/CocoaLumberjack.h, which is in a pod, right?

**Comment by TrevorFSmith** [comment]
Never mind, I opened the project instead of the workspace. Bleh.

**Pull request merged**
