### PR TITLE
wxrv:// as a protocol

### PR DESCRIPTION
**Pull request by Utopiah**

### CODE REVIEW

**Comment by aidinabedi** [comment]
@robomex: Has the WebXR Viewer on App Store been updated to include this?

**Comment by robomex** [comment]
@aidinabedi Hi Aidin – the App Store version of XR Viewer has this functionality.  This PR added a note about the protocol to the README.

For example, I have a list of links that start with "wxrv://" in my Notes app that I use for testing purposes.  Upon tapping one of those links, WebXR Viewer launches straight to that specific URL.  

Please let me know if you have any issues.

**Comment by aidinabedi** [comment]
@robomex Just noticed, hence why I removed the question. But thank you for the quick response!

**Comment by sael-you** [comment]
@robomex  sorry for  interacting in this ticket again, but seems that wxrv:// doesn't work on the latest version on the app store, i checked and found that the protocol has changed on the app plist to "xrviewer" but seems to only open the app without redirecting to the url

**Comment by Utopiah** [comment]
@sael-you unfortunately I don’t think the project is maintained. Also due to Mozilla strategy changes it might not be merged into Firefox proper anytime soon and anyway possible can’t prior to Apple brings WebXR to WebKit.

**Pull request merged**
